# -*- coding: utf-8 -*-
"""notebook.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1m02DbIihbTeTmgo5_GeCll7AruAn1MoC

# Proyek Klasifikasi Gambar: Intel Image Classification Dataset.
- **Nama:** Muh. Arifandi
- **Email:** arif76440@gmail.com
- **ID Dicoding:** arif76440

## Domain Proyek

Perkembangan teknologi Deep Learning memungkinkan komputer melakukan pengenalan objek visual dengan tingkat akurasi yang tinggi. Salah satu implementasi Deep Learning yang paling populer dalam bidang Computer Vision adalah klasifikasi gambar menggunakan Convolutional Neural Network (CNN).

Pada proyek ini dibangun model CNN untuk mengklasifikasikan gambar pemandangan alam menggunakan Intel Image Classification Dataset dengan lima kategori yaitu forest, glacier, mountain, sea, dan street.

Dataset dipilih karena memiliki jumlah gambar yang besar, variasi visual yang beragam, serta ukuran gambar asli yang tidak seragam sehingga cocok digunakan untuk melatih model klasifikasi gambar pada kasus nyata.

Selain membangun model klasifikasi, proyek ini juga melakukan konversi model ke format SavedModel, TensorFlow Lite, dan TensorFlow.js agar model dapat digunakan pada berbagai platform deployment seperti cloud, mobile, dan browser.

# Business Understanding

## Problem Statement

1. Bagaimana membangun model CNN untuk melakukan klasifikasi gambar pemandangan alam?

2. Bagaimana meningkatkan kemampuan model agar mampu melakukan generalisasi dengan baik terhadap gambar baru?

3. Bagaimana melakukan deployment model ke berbagai platform menggunakan SavedModel, TensorFlow Lite, dan TensorFlow.js?

## Goals

1. Mengembangkan model klasifikasi gambar berbasis Sequential CNN menggunakan layer Conv2D dan MaxPooling2D.

2. Mencapai akurasi model minimal 85% pada data testing.

3. Mengimplementasikan preprocessing dan data augmentation untuk meningkatkan kemampuan generalisasi model.

4. Menghasilkan model yang dapat digunakan pada berbagai platform deployment seperti TensorFlow SavedModel, TensorFlow Lite, dan TensorFlow.js.

## Solution Statements

Solusi yang digunakan pada proyek ini adalah:

- Menggunakan arsitektur Sequential CNN dengan beberapa layer Conv2D dan MaxPooling2D untuk melakukan ekstraksi fitur gambar.

- Mengimplementasikan data augmentation untuk meningkatkan variasi data training dan kemampuan generalisasi model.

- Menggunakan callback seperti EarlyStopping, ReduceLROnPlateau, dan ModelCheckpoint untuk meningkatkan stabilitas proses training.

- Menggunakan GlobalAveragePooling2D untuk mengurangi jumlah parameter dan meningkatkan efisiensi model.

- Mengonversi model ke format SavedModel, TensorFlow Lite, dan TensorFlow.js agar dapat digunakan pada berbagai platform deployment.

## Data Understanding

Dataset yang digunakan adalah Intel Image Classification Dataset.

Link Dataset:
https://www.kaggle.com/datasets/puneet6060/intel-image-classification

Pada proyek ini digunakan lima kategori gambar pemandangan alam, yaitu:

1. forest
2. glacier
3. mountain
4. sea
5. street

Dataset memiliki ukuran gambar yang tidak seragam sehingga diperlukan preprocessing berupa resize gambar sebelum proses training dilakukan.

## Import Semua Packages/Library yang Digunakan
"""

!pip install -q kaggle
!pip install -q tensorflowjs

import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os
import shutil
import tensorflowjs as tfjs

from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

from tensorflow.keras.preprocessing import image

"""## Data Preparation

### Data Loading

#### Upload Kaggle API
"""

from google.colab import files
files.upload()

"""#### Setup Kaggle API"""

!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

"""#### Download Dataset"""

!kaggle datasets download -d puneet6060/intel-image-classification

"""#### Extract Dataset"""

!unzip -q intel-image-classification.zip

"""#### Memilih 5 Kelas Dataset"""

selected_classes = [
    'forest',
    'glacier',
    'mountain',
    'sea',
    'street'
]

source_dir = '/content/seg_train/seg_train'

filtered_dir = '/content/intel_5class'

os.makedirs(filtered_dir, exist_ok=True)

for cls in selected_classes:

    shutil.copytree(
        os.path.join(source_dir, cls),
        os.path.join(filtered_dir, cls)
    )

print("5 kelas berhasil dibuat")

"""#### Menentukan Direktori Dataset"""

base_dir = '/content/intel_5class'

"""### Data Understanding

#### Menampilkan Kelas Dataset
"""

classes = sorted(os.listdir(base_dir))
classes

"""### Analisis Dataset

Dataset Intel Image Classification terdiri dari sekitar 25.000 gambar dengan 6 kategori pemandangan alam:

- buildings
- forest
- glacier
- mountain
- sea
- street

Dataset memiliki ukuran gambar yang tidak seragam sehingga diperlukan preprocessing berupa resize sebelum proses training dilakukan.

#### Menghitung Distribusi Dataset
"""

image_count = {}

for cls in classes:
    class_dir = os.path.join(base_dir, cls)
    image_count[cls] = len(os.listdir(class_dir))

image_count

"""#### Visualisasi Distribusi Dataset"""

plt.figure(figsize=(10,5))

plt.bar(
    image_count.keys(),
    image_count.values()
)

plt.title('Distribusi Dataset')
plt.xlabel('Class')
plt.ylabel('Jumlah Gambar')

plt.xticks(rotation=45)

plt.show()

"""Berdasarkan visualisasi distribusi dataset, jumlah gambar pada setiap kelas
relatif seimbang dengan rentang sekitar 2200–2500 gambar per kelas.

Kondisi ini membantu model melakukan proses pembelajaran secara lebih stabil
karena tidak terdapat perbedaan jumlah data yang terlalu signifikan antar kelas.

Kelas mountain memiliki jumlah gambar terbanyak, sedangkan kelas forest
dan sea memiliki jumlah gambar yang hampir sama.

#### Visualisasi Sample Gambar
"""

plt.figure(figsize=(12,10))

for i, cls in enumerate(classes):

    img_path = os.path.join(
        base_dir,
        cls,
        os.listdir(os.path.join(base_dir, cls))[0]
    )

    img = plt.imread(img_path)

    plt.subplot(3,2,i+1)

    plt.imshow(img)

    plt.title(cls)

    plt.axis('off')

plt.tight_layout()

plt.show()

"""Visualisasi sample gambar menunjukkan bahwa setiap kelas memiliki karakteristik
visual yang berbeda.

Kelas forest didominasi warna hijau dan pepohonan,
kelas glacier memiliki area bersalju,
kelas mountain memiliki kontur pegunungan,
kelas sea memiliki dominasi area air,
sedangkan kelas street menampilkan lingkungan perkotaan.

Perbedaan pola visual ini membantu model dalam mempelajari fitur unik
dari masing-masing kategori gambar.

### Data Preprocessing

#### Menentukan Parameter Dataset
"""

IMG_SIZE = (128,128)
BATCH_SIZE = 16
SEED = 42

"""#### Split Dataset"""

train_ds = tf.keras.utils.image_dataset_from_directory(
    base_dir,
    validation_split=0.3,
    subset='training',
    seed=SEED,
    image_size=IMG_SIZE,
    batch_size=BATCH_SIZE
)

"""#### Validation dan Test Dataset"""

val_test_ds = tf.keras.utils.image_dataset_from_directory(
    base_dir,
    validation_split=0.3,
    subset='validation',
    seed=SEED,
    image_size=IMG_SIZE,
    batch_size=BATCH_SIZE
)

"""#### Membagi Validation dan Test Set"""

val_batches = tf.data.experimental.cardinality(
    val_test_ds
)

test_ds = val_test_ds.take(
    val_batches // 2
)

val_ds = val_test_ds.skip(
    val_batches // 2
)

"""#### Menampilkan Nama Kelas"""

class_names = train_ds.class_names
class_names

"""#### Data Augmentation"""

# ================================================================
# DATA AUGMENTATION
# ================================================================

data_augmentation = tf.keras.Sequential([

    tf.keras.layers.RandomFlip(
        "horizontal"
    ),

    tf.keras.layers.RandomRotation(
        0.1
    ),

    tf.keras.layers.RandomZoom(
        0.1
    ),

    tf.keras.layers.RandomContrast(
        0.1
    )

], name='data_augmentation')

"""#### Menerapkan Augmentasi Hanya pada Training Set"""

train_ds = train_ds.map(
    lambda x, y: (
        data_augmentation(x, training=True),
        y
    )
)

"""#### Optimasi Dataset"""

AUTOTUNE = tf.data.AUTOTUNE

train_ds = train_ds.shuffle(200) \
                   .prefetch(buffer_size=AUTOTUNE)

val_ds = val_ds.prefetch(
    buffer_size=AUTOTUNE
)

test_ds = test_ds.prefetch(
    buffer_size=AUTOTUNE
)

"""## Modelling

Model CNN dibangun menggunakan arsitektur Sequential dengan beberapa layer Conv2D dan MaxPooling2D.

Layer convolution digunakan untuk mengekstraksi fitur visual dari gambar, sedangkan pooling digunakan untuk mengurangi dimensi fitur agar model lebih efisien.

GlobalAveragePooling2D digunakan untuk mengurangi jumlah parameter model sehingga model lebih ringan dan lebih cepat saat deployment.

#### Membangun Model Sequential
"""

# ================================================================
# MODEL CNN SEQUENTIAL
# ================================================================

model = tf.keras.Sequential([

    tf.keras.layers.Input(shape=(128,128,3)),

    tf.keras.layers.Rescaling(1./255),

    # BLOCK 1
    tf.keras.layers.Conv2D(
        32,
        (3,3),
        activation='relu',
        padding='same'
    ),
    tf.keras.layers.BatchNormalization(),
    tf.keras.layers.MaxPooling2D(2,2),

    # BLOCK 2
    tf.keras.layers.Conv2D(
        64,
        (3,3),
        activation='relu',
        padding='same'
    ),
    tf.keras.layers.BatchNormalization(),
    tf.keras.layers.MaxPooling2D(2,2),

    # BLOCK 3
    tf.keras.layers.Conv2D(
        128,
        (3,3),
        activation='relu',
        padding='same'
    ),
    tf.keras.layers.BatchNormalization(),
    tf.keras.layers.MaxPooling2D(2,2),

    # BLOCK 4
    tf.keras.layers.Conv2D(
        256,
        (3,3),
        activation='relu',
        padding='same'
    ),
    tf.keras.layers.BatchNormalization(),
    tf.keras.layers.MaxPooling2D(2,2),

    # BLOCK 5
    tf.keras.layers.Conv2D(
        512,
        (3,3),
        activation='relu',
        padding='same'
    ),
    tf.keras.layers.BatchNormalization(),
    tf.keras.layers.MaxPooling2D(2,2),

    tf.keras.layers.GlobalAveragePooling2D(),

    tf.keras.layers.Dense(
        512,
        activation='relu'
    ),

    tf.keras.layers.Dropout(0.5),

    tf.keras.layers.Dense(
        256,
        activation='relu'
    ),

    tf.keras.layers.Dropout(0.3),

    tf.keras.layers.Dense(
        len(class_names),
        activation='softmax'
    )
])

"""#### Model Summary"""

model.summary()

"""## Arsitektur Model

Model dibangun menggunakan arsitektur Sequential CNN yang terdiri dari beberapa layer Conv2D dan MaxPooling2D untuk melakukan ekstraksi fitur gambar secara bertahap.

Layer Conv2D digunakan untuk mempelajari pola visual seperti tekstur, tepi, dan bentuk objek pada gambar.

Layer MaxPooling2D digunakan untuk mengurangi dimensi fitur sehingga proses komputasi menjadi lebih efisien dan membantu mengurangi overfitting.

Setelah proses ekstraksi fitur selesai, model menggunakan GlobalAveragePooling2D dan Dense Layer untuk melakukan proses klasifikasi akhir terhadap lima kelas gambar.

#### Compile Model

##### Compile Arsitektur Model
"""

model.compile(
    optimizer=tf.keras.optimizers.Adam(
        learning_rate=1e-4
    ),
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

"""#### Callback

##### EarlyStopping
"""

earlystop = tf.keras.callbacks.EarlyStopping(
    monitor='val_accuracy',
    patience=5,
    restore_best_weights=True
)

"""##### Reduce Learning Rate"""

reduce_lr = tf.keras.callbacks.ReduceLROnPlateau(
    monitor='val_loss',
    factor=0.5,
    patience=2,
    min_lr=1e-7
)

"""##### Model Checkpoint"""

checkpoint = tf.keras.callbacks.ModelCheckpoint(
    'best_model.keras',
    monitor='val_accuracy',
    save_best_only=True
)

"""##### Menggabungkan Callback"""

callbacks = [
    earlystop,
    reduce_lr,
    checkpoint
]

"""#### Training Model"""

history = model.fit(
    train_ds,
    validation_data=val_ds,
    epochs=20,
    callbacks=callbacks
)

"""## Hasil Training

Model CNN berhasil dilatih menggunakan dataset Intel Image Classification dengan lima kategori gambar yaitu forest, glacier, mountain, sea, dan street.

Berdasarkan hasil training, model berhasil mencapai akurasi training di atas 85% dan validation accuracy di atas 85%. Hal ini menunjukkan bahwa model mampu mempelajari pola visual gambar dengan baik dan memiliki kemampuan generalisasi yang cukup stabil terhadap data baru.

Nilai loss juga mengalami penurunan secara bertahap selama proses training yang menunjukkan bahwa proses pembelajaran model berjalan dengan optimal.

Penggunaan BatchNormalization, Dropout, callback, dan data augmentation membantu meningkatkan stabilitas training serta mengurangi risiko overfitting.

## Evaluasi dan Visualisasi

#### Evaluasi Model
"""

train_loss, train_acc = model.evaluate(
    train_ds,
    verbose=0
)

test_loss, test_acc = model.evaluate(
    test_ds,
    verbose=0
)

print(f'Train Accuracy : {train_acc*100:.2f}%')
print(f'Test Accuracy  : {test_acc*100:.2f}%')

"""#### Plot Accuracy"""

plt.figure(figsize=(10,5))

plt.plot(
    history.history['accuracy'],
    label='Training Accuracy'
)

plt.plot(
    history.history['val_accuracy'],
    label='Validation Accuracy'
)

plt.title('Training dan Validation Accuracy')

plt.xlabel('Epoch')
plt.ylabel('Accuracy')

plt.legend()

plt.show()

"""Grafik accuracy menunjukkan bahwa akurasi training dan validation mengalami peningkatan secara konsisten selama proses training berlangsung.

Validation accuracy berhasil mencapai lebih dari 85% yang menunjukkan bahwa model memiliki performa klasifikasi yang baik terhadap data baru.

Kurva training dan validation yang relatif stabil menunjukkan bahwa model tidak mengalami overfitting secara signifikan.

#### Plot Loss
"""

plt.figure(figsize=(10,5))

plt.plot(
    history.history['loss'],
    label='Training Loss'
)

plt.plot(
    history.history['val_loss'],
    label='Validation Loss'
)

plt.title('Training dan Validation Loss')

plt.xlabel('Epoch')
plt.ylabel('Loss')

plt.legend()

plt.show()

"""Grafik loss menunjukkan bahwa nilai loss training dan validation mengalami penurunan selama proses training berlangsung.

Penurunan loss menunjukkan bahwa model semakin mampu mempelajari pola data dengan baik pada setiap epoch.

Kurva loss yang relatif stabil menunjukkan bahwa proses training berjalan dengan cukup optimal.

#### Confusion Matrix
"""

y_true = []
y_pred = []

for images, labels in test_ds:

    predictions = model.predict(
        images,
        verbose=0
    )

    y_true.extend(labels.numpy())

    y_pred.extend(
        np.argmax(predictions, axis=1)
    )

"""#### Visualisasi Confusion Matrix"""

cm = confusion_matrix(y_true, y_pred)

plt.figure(figsize=(10,8))

sns.heatmap(
    cm,
    annot=True,
    fmt='d',
    cmap='Blues',
    xticklabels=class_names,
    yticklabels=class_names
)

plt.xlabel('Predicted')
plt.ylabel('Actual')

plt.title('Confusion Matrix')

plt.show()

"""Confusion matrix menunjukkan bahwa sebagian besar gambar berhasil diprediksi dengan benar pada masing-masing kelas.

Beberapa kesalahan prediksi masih terjadi pada kelas yang memiliki karakteristik visual mirip, namun secara keseluruhan model mampu melakukan klasifikasi dengan performa yang baik dan stabil.

Hasil confusion matrix menunjukkan bahwa model memiliki kemampuan generalisasi yang cukup baik terhadap data testing.

#### Classification Report
"""

print(classification_report(
    y_true,
    y_pred,
    target_names=class_names
))

"""Berdasarkan classification report, model memiliki nilai precision, recall, dan f1-score yang cukup tinggi pada sebagian besar kelas.

Hal ini menunjukkan bahwa model mampu mengenali pola visual pada masing-masing kategori gambar dengan cukup baik.

Performa model yang stabil pada seluruh kelas menunjukkan bahwa proses training dan preprocessing berjalan secara optimal.

## Konversi Model

#### Save SavedModel
"""

model.export('saved_model')

"""## Konversi TensorFlow Lite

#### Convert TensorFlow Lite
"""

converter = tf.lite.TFLiteConverter.from_saved_model(
    'saved_model'
)

converter.optimizations = [
    tf.lite.Optimize.DEFAULT
]

tflite_model = converter.convert()

"""### Membuat Folder tflite"""

os.makedirs('tflite', exist_ok=True)

"""### Membuat Model tiflite"""

with open('tflite/model.tflite', 'wb') as f:
    f.write(tflite_model)

"""## Konversi TensorFlowJS

### Convert TFJS
"""

tfjs.converters.save_keras_model(
    model,
    "tfjs_model"
)

"""## Verifikasi TensorFlow Lite

### Load Interpreter
"""

interpreter = tf.lite.Interpreter(
    model_path='tflite/model.tflite'
)

interpreter.allocate_tensors()

print('TFLite berhasil diverifikasi')

"""### Membuat label.txt

#### Save Label
"""

with open('tflite/label.txt', 'w') as f:

    for label in class_names:
        f.write(label + '\n')

print("label.txt berhasil dibuat")

"""## Inference (Optional)

#### Upload Gambar Baru
"""

from google.colab import files

uploaded = files.upload()

"""#### Load dan Preprocessing Gambar"""

img_path = list(uploaded.keys())[0]

img = image.load_img(
    img_path,
    target_size=(150,150)
)

img_array = image.img_to_array(img)

img_array = np.expand_dims(
    img_array,
    axis=0
)

"""#### Prediksi Gambar"""

prediction = model.predict(
    img_array,
    verbose=0
)

predicted_class = class_names[
    np.argmax(prediction)
]

confidence = np.max(prediction) * 100

print(f'Prediction : {predicted_class}')
print(f'Confidence : {confidence:.2f}%')

"""#### Visualisasi Hasil Prediksi"""

plt.figure(figsize=(6,6))

plt.imshow(img)

plt.title(
    f'Prediction: {predicted_class}\n'
    f'Confidence: {confidence:.2f}%'
)

plt.axis('off')

plt.show()

"""Model berhasil melakukan prediksi terhadap gambar baru dengan cukup baik.

Hasil inference menunjukkan bahwa model mampu mengenali kategori gambar berdasarkan pola visual yang telah dipelajari selama proses training.

Inference dilakukan menggunakan model TensorFlow Lite sehingga model dapat digunakan pada deployment perangkat ringan seperti mobile dan edge device.

# Kesimpulan

Pada proyek ini berhasil dibangun model klasifikasi gambar menggunakan pendekatan Deep Learning berbasis Convolutional Neural Network (CNN) dengan arsitektur Sequential yang terdiri dari beberapa layer Conv2D dan MaxPooling2D.

Dataset yang digunakan merupakan Intel Image Classification Dataset dengan lima kategori gambar yaitu forest, glacier, mountain, sea, dan street.

Tahapan preprocessing dilakukan melalui resize gambar, pembagian dataset train, validation, dan test set, serta data augmentation untuk meningkatkan kemampuan generalisasi model.

Model berhasil mencapai akurasi training dan validation di atas 85% sehingga memenuhi kriteria submission.

Evaluasi menggunakan confusion matrix dan classification report menunjukkan bahwa model mampu melakukan klasifikasi gambar dengan performa yang cukup baik dan stabil pada seluruh kelas.

Selain itu, model berhasil dikonversi ke berbagai format deployment yaitu:

- SavedModel
- TensorFlow Lite
- TensorFlow.js

sehingga model dapat digunakan pada berbagai platform seperti cloud, mobile, maupun browser.

Berdasarkan seluruh hasil evaluasi, model yang dibangun telah memenuhi seluruh kriteria submission image classification dan mampu melakukan klasifikasi gambar secara akurat dan stabil.

## Membuat requirements.txt
"""

!pip freeze > requirements.txt